/*
* NOTICE:
* The U.S. Army Corps of Engineers, Risk Management Center (USACE-RMC) makes no guarantees about
* the results, or appropriateness of outputs, obtained from this software.
*
* LIST OF CONDITIONS:
* Redistribution and use in source and binary forms, with or without modification, are permitted
* provided that the following conditions are met:
* ● Redistributions of source code must retain the above notice, this list of conditions, and the
* following disclaimer.
* ● Redistributions in binary form must reproduce the above notice, this list of conditions, and
* the following disclaimer in the documentation and/or other materials provided with the distribution.
* ● The names of the U.S. Government, the U.S. Army Corps of Engineers, the Institute for Water
* Resources, or the Risk Management Center may not be used to endorse or promote products derived
* from this software without specific prior written permission. Nor may the names of its contributors
* be used to endorse or promote products derived from this software without specific prior
* written permission.
*
* DISCLAIMER:
* THIS SOFTWARE IS PROVIDED BY THE U.S. ARMY CORPS OF ENGINEERS RISK MANAGEMENT CENTER
* (USACE-RMC) "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO,
* THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
* DISCLAIMED. IN NO EVENT SHALL USACE-RMC BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
* SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
* PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
* INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
* LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
* THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
*/

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Diagnostics;
using System.IO;
using System.Linq;
using System.Text;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Documents;
using System.Windows.Input;
using System.Windows.Media;
using System.Windows.Media.Effects;
using ExpressionParser;
using ExpressionParser.Parser;
using QuickHelp;

namespace DatabaseControls
{
    /// <summary>
    /// A custom TextBox control with advanced expression parsing and syntax highlighting capabilities.
    /// </summary>
    /// <remarks>
    /// This control extends the standard WPF TextBox to provide:
    /// <list type="bullet">
    /// <item><description>Real-time syntax highlighting with 8 levels of colored parentheses</description></item>
    /// <item><description>Floating TextBlock overlay displaying formatted expression with 2-second delay</description></item>
    /// <item><description>Expression parsing with error detection and validation</description></item>
    /// <item><description>Clickable function names with integrated help documentation</description></item>
    /// <item><description>Background worker for delayed display updates</description></item>
    /// <item><description>Support for data table field references and type checking</description></item>
    /// </list>
    /// The control is designed for use in field calculator and expression editor scenarios
    /// where users need to write complex mathematical or logical expressions with visual feedback.
    /// </remarks>
    public class ExpressionTextBox : TextBox
    {
        #region Private Fields

        /// <summary>
        /// Stack to track parenthesis colors for proper nesting visualization.
        /// </summary>
        private Stack<SolidColorBrush> _parenColors;

        /// <summary>
        /// List of 8 predefined colors used for parenthesis highlighting at different nesting levels.
        /// </summary>
        private List<SolidColorBrush> _colorList;

        /// <summary>
        /// Floating TextBlock overlay that displays the formatted expression with syntax highlighting.
        /// </summary>
        private TextBlock _textBlock;

        /// <summary>
        /// Background worker that manages the 2-second delay before displaying the TextBlock overlay.
        /// </summary>
        private BackgroundWorker _bw;

        /// <summary>
        /// Tracks the current number of lines in the TextBox to detect changes.
        /// </summary>
        private int _numLines;

        /// <summary>
        /// Stopwatch used to track elapsed time for the background worker delay.
        /// </summary>
        private Stopwatch _s;

        /// <summary>
        /// The parsed expression tree generated by the parser.
        /// </summary>
        private ParseTreeNode? _tree;

        /// <summary>
        /// The result of evaluating the expression, or an error message if parsing failed.
        /// </summary>
        private string _result = string.Empty;

        /// <summary>
        /// Indicates whether field name comparisons should be case-sensitive.
        /// </summary>
        private bool _isCaseSensitive;

        /// <summary>
        /// List of column/field header names available for use in expressions.
        /// </summary>
        private List<string>? _headers;

        /// <summary>
        /// List of data types corresponding to each header in the _headers list.
        /// </summary>
        private List<Type>? _headertypes;

        /// <summary>
        /// Array containing the first row of data from the table, used for expression evaluation.
        /// </summary>
        private object[]? _firstRowOfData;

        /// <summary>
        /// The expected output type for the expression result.
        /// </summary>
        private TypeEnum _outputType;

        #endregion

        #region Events

        /// <summary>
        /// Occurs when the number of lines in the TextBox changes.
        /// Used internally to adjust the TextBlock overlay position.
        /// </summary>
        private event Action? NumLinesChanged;

        /// <summary>
        /// Occurs when parsing errors are found in the expression.
        /// </summary>
        /// <param name="treeIsNothing">True if the parse tree is null; false if errors exist in the tree.</param>
        public event Action<bool>? ErrorsFound;

        /// <summary>
        /// Occurs when the expression is successfully parsed and evaluated without errors.
        /// </summary>
        public event Action? ParseSuccess;

        #endregion

        #region Properties

        /// <summary>
        /// Gets or sets whether field name comparisons should be case-sensitive during parsing.
        /// </summary>
        /// <remarks>
        /// Changing this property triggers a re-parse of the expression.
        /// </remarks>
        public bool IsCaseSensitive
        {
            get => _isCaseSensitive;
            set
            {
                _isCaseSensitive = value;
                Parse();
            }
        }

        /// <summary>
        /// Gets the parsed expression tree.
        /// </summary>
        /// <remarks>
        /// Returns null if the expression has not been parsed or if parsing failed.
        /// </remarks>
        public ParseTreeNode? GetTree => _tree;

        /// <summary>
        /// Gets the result of evaluating the expression.
        /// </summary>
        /// <remarks>
        /// Returns the evaluated result as a string, or an error message if parsing or evaluation failed.
        /// Possible error messages include: "No rows in database", "Tree contains errors",
        /// "Invalid Syntax, check Error Log", "Exception", or an empty string.
        /// </remarks>
        public string GetResult => _result;

        /// <summary>
        /// Sets the list of column/field header names available for use in expressions.
        /// </summary>
        public List<string>? SetHeaders
        {
            set => _headers = value;
        }

        /// <summary>
        /// Sets the list of data types corresponding to each header.
        /// </summary>
        /// <remarks>
        /// The types in this list must correspond positionally to the headers in SetHeaders.
        /// </remarks>
        public List<Type>? SetHeaderTypes
        {
            set => _headertypes = value;
        }

        /// <summary>
        /// Gets the TextBlock overlay that displays the formatted expression.
        /// </summary>
        /// <remarks>
        /// This TextBlock should be added to a parent container (typically a Grid) to display properly.
        /// </remarks>
        public TextBlock GetTextBlock => _textBlock;

        /// <summary>
        /// Sets the expected output type for the expression.
        /// </summary>
        /// <remarks>
        /// Accepts standard .NET types and maps them to the parser's TypeEnum values.
        /// Supported types: Double, Boolean, String, Int32, Single, Byte, Short, and null (UnDeclared).
        /// Shows a message box if an unsupported type is provided.
        /// </remarks>
        public Type? SetOutputType
        {
            set
            {
                if (value == typeof(double))
                    _outputType = TypeEnum.Dub;
                else if (value == typeof(bool))
                    _outputType = TypeEnum.Bool;
                else if (value == typeof(string))
                    _outputType = TypeEnum.Str;
                else if (value == typeof(int))
                    _outputType = TypeEnum.Int;
                else if (value == typeof(float))
                    _outputType = TypeEnum.Dub;
                else if (value == typeof(byte))
                    _outputType = TypeEnum.byt;
                else if (value == typeof(short))
                    _outputType = TypeEnum.Shrt;
                else if (value == null)
                    _outputType = TypeEnum.UnDeclared;
                else
                    GenericControls.MessageBox.Show("The type of the selected header is not supported for output");
            }
        }

        /// <summary>
        /// Sets the first row of data from the table, used for expression evaluation.
        /// </summary>
        /// <remarks>
        /// The objects in this array must correspond positionally to the headers and types
        /// specified in SetHeaders and SetHeaderTypes.
        /// </remarks>
        public object[]? SetDataForFirstRow
        {
            set => _firstRowOfData = value;
        }

        #endregion

        #region Constructor

        /// <summary>
        /// Initializes a new instance of the ExpressionTextBox class.
        /// </summary>
        /// <remarks>
        /// Sets up the background worker, TextBlock overlay, color list for syntax highlighting,
        /// and subscribes to necessary events.
        /// </remarks>
        public ExpressionTextBox()
        {
            _outputType = TypeEnum.UnDeclared;

            // Initialize stopwatch for background worker delay
            _s = new Stopwatch();

            // Initialize and configure background worker
            _bw = new BackgroundWorker
            {
                WorkerSupportsCancellation = true
            };
            _bw.DoWork += SwStart;
            _bw.RunWorkerCompleted += RemoveTextBlock;

            // Configure TextBox wrapping
            TextWrapping = TextWrapping.Wrap;

            // Initialize and configure the floating TextBlock overlay
            _textBlock = new TextBlock
            {
                TextWrapping = TextWrapping.Wrap,
                Margin = new Thickness(5, 16, 5, 0),
                Background = new SolidColorBrush(Color.FromArgb(230, 240, 240, 240)),
                Effect = new DropShadowEffect(),
                Visibility = Visibility.Hidden,
                HorizontalAlignment = HorizontalAlignment.Left,
                VerticalAlignment = VerticalAlignment.Top
            };

            _numLines = 1;

            // Subscribe to TextBlock mouse events for background worker control
            _textBlock.MouseEnter += (s, e) => CancelBW();
            _textBlock.MouseLeave += (s, e) => StartBW();

            // Subscribe to NumLinesChanged event
            NumLinesChanged += ShiftDownward;

            // Set Grid row for TextBlock (assumes parent is a Grid)
            Grid.SetRow(_textBlock, 1);

            // Initialize parenthesis color stack
            _parenColors = new Stack<SolidColorBrush>();

            // Initialize the list of 8 colors for parenthesis highlighting
            _colorList = new List<SolidColorBrush>
            {
                new SolidColorBrush(Color.FromArgb(255, 255, 0, 0)),     // Red
                new SolidColorBrush(Color.FromArgb(255, 0, 255, 0)),     // Green
                new SolidColorBrush(Color.FromArgb(255, 255, 0, 255)),   // Magenta
                new SolidColorBrush(Color.FromArgb(255, 0, 204, 204)),   // Cyan
                new SolidColorBrush(Color.FromArgb(255, 255, 130, 0)),   // Orange
                new SolidColorBrush(Color.FromArgb(255, 0, 255, 128)),   // Spring Green
                new SolidColorBrush(Color.FromArgb(255, 157, 0, 255)),   // Purple
                new SolidColorBrush(Color.FromArgb(255, 102, 204, 0))    // Yellow Green
            };

            // Subscribe to KeyUp event for parsing
            KeyUp += Expression_KeyUp;
        }

        #endregion

        #region TextBlock Events

        /// <summary>
        /// Adjusts the TextBlock overlay's vertical position when the number of lines changes.
        /// </summary>
        private void ShiftDownward()
        {
            _textBlock.Margin = new Thickness(
                _textBlock.Margin.Left,
                5 + (16 * LineCount),
                _textBlock.Margin.Right,
                _textBlock.Margin.Bottom);
            _numLines = LineCount;
        }

        /// <summary>
        /// Hides the TextBlock overlay after the background worker completes.
        /// </summary>
        private void RemoveTextBlock(object? sender, RunWorkerCompletedEventArgs e)
        {
            _textBlock.Visibility = Visibility.Hidden;
        }

        /// <summary>
        /// Starts the background worker to begin the 2-second delay timer.
        /// </summary>
        private void StartBW()
        {
            _s.Restart();
            if (!_bw.IsBusy)
                _bw.RunWorkerAsync();
        }

        /// <summary>
        /// Cancels the background worker delay by stopping the stopwatch.
        /// </summary>
        private void CancelBW()
        {
            _s.Stop();
        }

        /// <summary>
        /// Background worker method that waits for 2 seconds (2000 milliseconds).
        /// </summary>
        private void SwStart(object? sender, DoWorkEventArgs e)
        {
            while (_s.ElapsedMilliseconds < 2000)
            {
                // Wait until 2 seconds have elapsed
            }
        }

        #endregion

        #region TextBlock Text

        /// <summary>
        /// Adds formatted text to the TextBlock overlay with syntax highlighting.
        /// </summary>
        /// <param name="pos">The position of the token in the expression (not currently used).</param>
        /// <param name="token">The type of token being added.</param>
        /// <param name="text">The text content of the token.</param>
        /// <param name="helpdoc">The help documentation path for the token, if applicable.</param>
        /// <remarks>
        /// This method applies different formatting based on the token type:
        /// <list type="bullet">
        /// <item><description>Left parentheses push a new color onto the stack and are colored accordingly</description></item>
        /// <item><description>Right parentheses pop a color from the stack and are colored to match their partner</description></item>
        /// <item><description>Tokens with help documentation are formatted as clickable hyperlinks</description></item>
        /// <item><description>All other tokens are added as plain text</description></item>
        /// </list>
        /// </remarks>
        private void SetRichText(int pos, TokenEnum token, string text, string helpdoc)
        {
            _textBlock.Visibility = Visibility.Hidden;
            _textBlock.MaxWidth = ActualWidth - ((_textBlock.Margin.Left - Margin.Left) + (_textBlock.Margin.Right - Margin.Right));

            if (string.IsNullOrEmpty(helpdoc))
            {
                if (token == TokenEnum.LPAREN)
                {
                    // Push new color for left parenthesis
                    _parenColors.Push(_colorList[_parenColors.Count % _colorList.Count]);
                    _textBlock.Inlines.Add(text);
                    _textBlock.Inlines.LastInline.Foreground = _parenColors.Peek();
                }
                else if (token == TokenEnum.RPAREN)
                {
                    // Pop color for right parenthesis
                    if (_parenColors.Count > 0)
                    {
                        _textBlock.Inlines.Add(text);
                        _textBlock.Inlines.LastInline.Foreground = _parenColors.Pop();
                    }
                    else
                    {
                        _textBlock.Inlines.Add(text);
                    }
                }
                else
                {
                    // Regular text
                    _textBlock.Inlines.Add(text);
                }
            }
            else
            {
                // Create clickable hyperlink for function names
                var r = new Bold(new Run(text));
                var link = new Hyperlink(r)
                {
                    Tag = text,
                    NavigateUri = new Uri(helpdoc, UriKind.Relative),
                    IsEnabled = true
                };
                link.Click += Link_RequestNavigate;
                _textBlock.Inlines.Add(link);
            }

            _textBlock.Visibility = Visibility.Visible;
        }

        /// <summary>
        /// Handles hyperlink clicks to show help documentation for functions.
        /// </summary>
        /// <param name="sender">The hyperlink that was clicked.</param>
        /// <param name="e">The routed event arguments.</param>
        private void Link_RequestNavigate(object sender, RoutedEventArgs e)
        {
            var link = (Hyperlink)sender;
            var tmp = link.NavigateUri.ToString().Split('.');

            // Extract file string from URI (skip first part which is assembly name)
            var filestring = tmp[1];
            for (int i = 2; i < tmp.Length; i++)
            {
                filestring = filestring + "." + tmp[i];
            }

            // Show help dialog
            if (_tree != null)
            {
                var hd = new HelpDialog(
                    filestring,
                    link.Tag.ToString()!,
                    _tree.GetType().Assembly.FullName!,
                    _tree.GetType().Namespace!);
                hd.Show();
            }
        }

        #endregion

        #region Parsing

        /// <summary>
        /// Parses and evaluates the expression in the TextBox.
        /// </summary>
        /// <remarks>
        /// This method performs the following steps:
        /// <list type="number">
        /// <item><description>Validates that data is available for evaluation</description></item>
        /// <item><description>Initializes the syntax highlighting system</description></item>
        /// <item><description>Starts the background worker for delayed TextBlock display</description></item>
        /// <item><description>Tokenizes and parses the expression text</description></item>
        /// <item><description>Evaluates the expression if parsing succeeds</description></item>
        /// <item><description>Raises appropriate events based on the parsing result</description></item>
        /// </list>
        /// Events raised:
        /// <list type="bullet">
        /// <item><description>ParseSuccess: When expression is valid and evaluates successfully</description></item>
        /// <item><description>ErrorsFound(true): When parsing returns null tree or throws exception</description></item>
        /// <item><description>ErrorsFound(false): When tree contains syntax or semantic errors</description></item>
        /// </list>
        /// </remarks>
        public void Parse()
        {
            // Check if data is available
            if (_firstRowOfData == null)
            {
                _result = "No rows in database";
                ParseSuccess?.Invoke();
                return;
            }

            // Initialize syntax highlighting
            _parenColors = new Stack<SolidColorBrush>();
            _textBlock.Inlines.Clear();

            // Check if line count changed
            if (_numLines != LineCount)
                NumLinesChanged?.Invoke();

            // Start background worker for delayed display
            _s.Restart();
            if (!_bw.IsBusy)
                _bw.RunWorkerAsync();

            // Convert text to byte stream for scanner
            var strbytes = new UTF8Encoding().GetBytes(Text);
            var ms = new MemoryStream(strbytes);
            var scanner = new Scanner(ms);
            var parser = new Parser(scanner);

            // Subscribe to token events for syntax highlighting
            parser.TokenFound += SetRichText;

            // Configure parser settings
            ParseTreeNode.IsCaseSensitive = _isCaseSensitive;
            ParseTreeNode.RowOrCellNum = 0;

            try
            {
                // Parse the expression
                _tree = parser.Parse(_headers, _headertypes, _outputType);
                _textBlock.Inlines.Add(" ");

                if (_tree != null)
                {
                    if (_tree.GetParseErrors.Count > 0)
                    {
                        // Parse errors found
                        if (_tree.ContainsError)
                        {
                            _result = "Tree contains errors";
                            ErrorsFound?.Invoke(false);
                        }
                        else
                        {
                            _result = "Invalid Syntax, check Error Log";
                            ErrorsFound?.Invoke(false);
                        }
                    }
                    else
                    {
                        // Successful parse - evaluate expression
                        if (_tree.containsVariable)
                        {
                            var importantHeaders = GetColumnsFromTree(_tree);
                            if (importantHeaders.Count > 0)
                            {
                                _tree.SetColNums(importantHeaders);
                                _tree.Update(GetDataFromDatabaseForUniqueColumns(importantHeaders));
                            }
                        }

                        _result = _tree.Evaluate.GetResult.ToString()!;
                        ParseSuccess?.Invoke();
                    }
                }
                else
                {
                    // Parser returned null tree
                    _result = string.Empty;
                    ErrorsFound?.Invoke(true);
                }
            }
            catch (Exception)
            {
                // Exception during parsing
                _result = "Exception";
                ErrorsFound?.Invoke(true);
            }
        }

        /// <summary>
        /// Handles the KeyUp event to trigger parsing when the user types.
        /// </summary>
        private void Expression_KeyUp(object sender, KeyEventArgs e)
        {
            Parse();
        }

        /// <summary>
        /// Extracts the unique list of column names referenced in the parse tree.
        /// </summary>
        /// <param name="tree">The parse tree to extract column names from.</param>
        /// <returns>A distinct list of column/field names used in the expression.</returns>
        private List<string> GetColumnsFromTree(ParseTreeNode tree)
        {
            return tree.GetHeaderNames.Distinct().ToList();
        }

        /// <summary>
        /// Retrieves data values for the specified columns from the first row of data.
        /// </summary>
        /// <param name="uniqueHeaders">The list of unique column names to retrieve data for.</param>
        /// <returns>An array of objects containing the data values in the same order as uniqueHeaders.</returns>
        private object[] GetDataFromDatabaseForUniqueColumns(List<string> uniqueHeaders)
        {
            var data = new List<object>();
            if (_firstRowOfData == null || _headers == null)
                return data.ToArray();

            for (int i = 0; i < uniqueHeaders.Count; i++)
            {
                data.Add(_firstRowOfData[_headers.IndexOf(uniqueHeaders[i])]);
            }

            return data.ToArray();
        }

        #endregion
    }
}
