<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows</TargetFramework>
    <RootNamespace>Demo_ProjectUI</RootNamespace>
    <AssemblyName>Demo_ProjectUI</AssemblyName>
    <Nullable>disable</Nullable>
    <UseWPF>true</UseWPF>
    <ImplicitUsings>enable</ImplicitUsings>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\FrameworkInterfaces\FrameworkInterfaces.csproj" />
    <ProjectReference Include="..\FrameworkUI\FrameworkUI.csproj" />
    <ProjectReference Include="..\Themes\Themes.csproj" />
    <ProjectReference Include="..\SoftwareUpdate\SoftwareUpdate.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="Xceed.Wpf.AvalonDock">
      <HintPath>..\FrameworkUI\Resources\Xceed.Wpf.AvalonDock.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
