<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <IsPackable>true</IsPackable>
    <IncludeBuildOutput>false</IncludeBuildOutput>
    <Version>1.0.3</Version>
    <NuspecFile>RMC.Wpf.Framework.Models.nuspec</NuspecFile>
    <NuspecBasePath>$(MSBuildProjectDirectory)</NuspecBasePath>
    <NuspecProperties>configuration=$(Configuration);version=$(Version);closedXmlVersion=$(ClosedXmlVersion);documentFormatOpenXmlVersion=$(DocumentFormatOpenXmlVersion);excelNumberFormatVersion=$(ExcelNumberFormatVersion);fastMemberVersion=$(FastMemberVersion);sourceGearSqlite3Version=$(SourceGearSqlite3Version);systemDataSQLiteVersion=$(SystemDataSQLiteVersion)</NuspecProperties>
  </PropertyGroup>
</Project>
