<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>disable</Nullable>
    <UseWPF>true</UseWPF>
    <ImplicitUsings>enable</ImplicitUsings>
	<GenerateAssemblyInfo>false</GenerateAssemblyInfo>
	<SignAssembly>true</SignAssembly>
    <AssemblyOriginatorKeyFile>sn.snk</AssemblyOriginatorKeyFile>
    <NoWarn>CS1616;CA1416;SYSLIB0003;SYSLIB0004</NoWarn>
    <SatelliteResourceLanguages>en</SatelliteResourceLanguages>
  </PropertyGroup>

  <ItemGroup>
    <Resource Include="Themes\Generic\Images\*.png" />
  </ItemGroup>


</Project>
