<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net9.0-windows;</TargetFrameworks>
    <Nullable>disable</Nullable>
    <UseWPF>true</UseWPF>
    <ImplicitUsings>enable</ImplicitUsings>
	<GenerateAssemblyInfo>false</GenerateAssemblyInfo>
	<SignAssembly>true</SignAssembly>
    <AssemblyOriginatorKeyFile>sn.snk</AssemblyOriginatorKeyFile>
    <NoWarn>CS1616;CA1416;SYSLIB0003;SYSLIB0004</NoWarn>
    <SatelliteResourceLanguages>en</SatelliteResourceLanguages>
  </PropertyGroup>

  <ItemGroup>
    <Resource Include="Themes\Generic\Images\*.png" />
  </ItemGroup>

  <PropertyGroup Condition="'$(TargetFramework)' == 'net481'">
	<LangVersion>latest</LangVersion>
  </PropertyGroup>

</Project>
