<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net9.0-windows;</TargetFrameworks>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
    <ImplicitUsings>enable</ImplicitUsings>
	<GenerateAssemblyInfo>false</GenerateAssemblyInfo>
	<SignAssembly>true</SignAssembly>
    <AssemblyOriginatorKeyFile>sn.snk</AssemblyOriginatorKeyFile>
  </PropertyGroup>
  
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <Optimize>False</Optimize>
    <WarningLevel>1</WarningLevel>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <WarningLevel>1</WarningLevel>
  </PropertyGroup>
  
  <PropertyGroup Condition="'$(TargetFramework)' == 'net481'">
	<LangVersion>latest</LangVersion>
  </PropertyGroup>
  
</Project>
