using System.ComponentModel;
using System.Diagnostics;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Data;
using System.Windows.Input;
using System.Windows.Media;

namespace GenericControls
{
    /// <summary>
    /// A DataGrid with built-in validation support for cell values, including error highlighting and validation rules.
    /// </summary>
    /// <remarks>
    /// <para>
    ///     <b> Authors: </b>
    /// <list type="bullet">
    /// <item><description>
    ///     Woodrow Fields, USACE Risk Management Center, woodrow.l.fields@usace.army.mil
    /// </description></item>
    /// <item><description>
    ///     Haden Smith, USACE Risk Management Center, cole.h.smith@usace.army.mil
    /// </description></item>
    /// </list>
    /// </para>
    /// </remarks>
    public sealed class ValidationDataGrid : CopyPasteDataGrid
    {

        #region Construction
        /// <summary>
        /// Initializes a new instance of the <see cref="ValidationDataGrid"/> class.
        /// Hooks into key DataGrid events and applies validation styling and behavior.
        /// </summary>
        public ValidationDataGrid()
        {
            AutoGeneratingColumn += Grid_AutoGeneratingColumn;
            Loaded += (sender, e) => ValidateTable();
            RowsAdded += Grid_RowsAdded;
            PreviewDeleteRows += Grid_PreviewDeleteRows;
            RowsDeleted += Grid_RowsDeleted;
            PreviewPasteData += Grid_PreviewPasteData;
            DataPasted += Grid_DataPasted;
            SelectedCellsChanged += (sender, e) =>
                {
                    if (((IEditableCollectionView)Items).IsEditingItem == false)
                        return;
                    if (e.AddedCells.Count > 0 && !IsReadOnly)
                    {
                        try
                        {
                            CommitEdit();
                        }
                        catch (Exception ex)
                        {
                            // The previous cell may still be editing when selection changes
                            Debug.WriteLine(ex);
                        }
                    }
                };
            Resources.Add(SystemColors.InactiveSelectionHighlightBrushKey, new SolidColorBrush(Colors.DarkGray));
            AutoGeneratedColumns += ValidationDataGrid_AutoGeneratedColumns;
        }

        #endregion

        #region Members

        private Dictionary<string, Type> _propertyTypes = new Dictionary<string, Type>();


        /// <summary>
        /// Identifies the <see cref="ErrorCellBorderBrush"/> dependency property.
        /// </summary>
        public static readonly DependencyProperty ErrorCellBorderBrushProperty = DependencyProperty.Register(nameof(ErrorCellBorderBrush), typeof(Brush), typeof(ValidationDataGrid), new FrameworkPropertyMetadata(Brushes.Red));

        /// <summary>
        /// Brush used to highlight the border of cells with validation errors.
        /// </summary>
        public Brush ErrorCellBorderBrush
        {
            get
            {
                return (Brush)GetValue(ErrorCellBorderBrushProperty);
            }
            set
            {
                SetValue(ErrorCellBorderBrushProperty, value);
            }
        }

        /// <summary>
        /// Identifies the <see cref="ErrorCellBackgroundBrush"/> dependency property.
        /// </summary>
        public static readonly DependencyProperty ErrorCellBackgroundBrushProperty = DependencyProperty.Register(nameof(ErrorCellBackgroundBrush), typeof(Brush), typeof(ValidationDataGrid), new FrameworkPropertyMetadata(new SolidColorBrush(Color.FromArgb(255, 247, 182, 175))));

        /// <summary>
        /// Brush used to highlight the background of cells with validation errors.
        /// </summary>
        public Brush ErrorCellBackgroundBrush
        {
            get
            {
                return (Brush)GetValue(ErrorCellBackgroundBrushProperty);
            }
            set
            {
                SetValue(ErrorCellBackgroundBrushProperty, value);
            }
        }


        /// <summary>
        /// Gets a value indicating whether validation should be suppressed.
        /// </summary>
        public bool SuppressValidation { get; private set; } = false;


        /// <summary>
        /// Gets a value indicating whether bulk validation is currently being performed.
        /// </summary>
        public bool PerformingBulkValidation { get; private set; } = false;

        #endregion

        #region Methods

        /// <summary>
        /// Determines whether the BeginEdit command can execute.
        /// </summary>
        /// <param name="e">The event arguments containing the execution state.</param>
        protected override void OnCanExecuteBeginEdit(CanExecuteRoutedEventArgs e)
        {
            e.CanExecute = true;
            e.Handled = true;
        }

        /// <summary>
        /// Handles automatic column generation logic for display, style, and validation binding.
        /// </summary>
        /// <param name="sender">The DataGrid triggering the event.</param>
        /// <param name="e">Event data describing the generated column.</param>
        private void Grid_AutoGeneratingColumn(object sender, DataGridAutoGeneratingColumnEventArgs e)
        {
            if (e.PropertyName.Equals(nameof(DataGridRowItem.RuleMap)))
            {
                e.Cancel = true;
                return;
            }
            if (ItemsSource == null)
                return;
            IList<object> il = (IList<object>)ItemsSource;
            if (il.FirstOrDefault() is not DataGridRowItem d)
                return;
            e.Cancel = !d.IsGridDisplayable(e.PropertyName);
            if (e.Cancel)
                return;
            string prettyheader = d.PropertyDisplayName(e.PropertyName);
            if (!(prettyheader == null) && !prettyheader.Equals(""))
                e.Column.Header = prettyheader;
            // 
            if (_propertyTypes.ContainsKey(e.PropertyName))
            {
                _propertyTypes[e.PropertyName] = e.PropertyType;
            }
            else
            {
                _propertyTypes.Add(e.PropertyName, e.PropertyType);
            }
        }

        /// <summary>
        /// Validates and configures the auto-generated columns, setting up validation triggers and styles.
        /// </summary>
        /// <param name="sender">The DataGrid triggering the event.</param>
        /// <param name="e">Event data for the auto-generated columns event.</param>
        private void ValidationDataGrid_AutoGeneratedColumns(object sender, EventArgs e)
        {
            foreach (var column in Columns)
            {
                if (column.GetType() == typeof(DataGridTextColumn))
                {

                    // text column 
                    DataGridTextColumn dgtc = (DataGridTextColumn)column;
                    dgtc.Width = new DataGridLength(1d, DataGridLengthUnitType.Star);
                    string propertyName = ((Binding)dgtc.Binding).Path.Path.ToString();
                    // 
                    // First set the column editing style
                    // 
                    if (dgtc.EditingElementStyle == null)
                    {
                        dgtc.EditingElementStyle = new Style(typeof(TextBox), FindImplicitStyle<TextBox>());
                    }
                    else
                    {
                        var newStyle = new Style(typeof(TextBox), FindImplicitStyle<TextBox>());
                        foreach (var setter in dgtc.EditingElementStyle.Setters)
                            newStyle.Setters.Add(setter);
                        dgtc.EditingElementStyle = newStyle;
                    }
                    // 
                    // Dim textboxstyle As New Style(GetType(TextBox))
                    dgtc.EditingElementStyle.Setters.Add(new Setter(BorderThicknessProperty, new Thickness(0d)));
                    dgtc.EditingElementStyle.Setters.Add(new Setter(PaddingProperty, new Thickness(0d)));
                    dgtc.EditingElementStyle.Setters.Add(new Setter(HeightProperty, RowHeight));
                    dgtc.EditingElementStyle.Setters.Add(new Setter(VerticalContentAlignmentProperty, VerticalAlignment.Center));
                    switch (_propertyTypes[propertyName])
                    {
                        case var @case when @case == typeof(double):
                        case var case1 when case1 == typeof(float):
                        case var case2 when case2 == typeof(decimal):
                            {
                                var textBoxDoubleSetter = new EventSetter(PreviewTextInputEvent, new TextCompositionEventHandler(Double_PreviewTextInput));
                                var textBoxChangedDblSetter = new EventSetter(System.Windows.Controls.Primitives.TextBoxBase.TextChangedEvent, new TextChangedEventHandler(Double_TextChanged));
                                dgtc.EditingElementStyle.Setters.Add(textBoxDoubleSetter);
                                dgtc.EditingElementStyle.Setters.Add(textBoxChangedDblSetter);
                                break;
                            }
                        case var case3 when case3 == typeof(long):
                        case var case4 when case4 == typeof(ulong):
                        case var case5 when case5 == typeof(int):
                        case var case6 when case6 == typeof(uint):
                        case var case7 when case7 == typeof(short):
                        case var case8 when case8 == typeof(ushort):
                        case var case9 when case9 == typeof(byte):
                        case var case10 when case10 == typeof(sbyte):
                            {
                                var textBoxIntegerSetter = new EventSetter(PreviewTextInputEvent, new TextCompositionEventHandler(Int_PreviewTextInput));
                                var textBoxChangedIntSetter = new EventSetter(System.Windows.Controls.Primitives.TextBoxBase.TextChangedEvent, new TextChangedEventHandler(Int_TextChanged));
                                dgtc.EditingElementStyle.Setters.Add(textBoxIntegerSetter);
                                dgtc.EditingElementStyle.Setters.Add(textBoxChangedIntSetter);
                                break;
                            }
                    }

                    // Set the cell style for error collection.
                    // Use this.CellStyle as BasedOn — it is set to ValidationDataGridCellStyle
                    // by the ValidationDataGridStyle, which contains the themed ControlTemplate
                    // with the blue IsKeyboardFocusWithin border trigger. FindImplicitStyle<DataGridCell>()
                    // resolves to the WPF default style (black/system borders) instead.
                    if (dgtc.CellStyle == null)
                    {
                        dgtc.CellStyle = new Style(typeof(DataGridCell), CellStyle);
                    }
                    else
                    {
                        var newStyle = new Style(typeof(DataGridCell), CellStyle);
                        foreach (var setter in dgtc.CellStyle.Setters)
                            newStyle.Setters.Add(setter);
                        dgtc.CellStyle = newStyle;
                    }
                    //
                    // grid element style
                    if (dgtc.ElementStyle == null)
                    {
                        dgtc.ElementStyle = new Style(typeof(TextBlock), FindImplicitStyle<TextBlock>());
                    }
                    else
                    {
                        var newStyle = new Style(typeof(TextBlock), FindImplicitStyle<TextBlock>());
                        foreach (var setter in dgtc.ElementStyle.Setters)

                            newStyle.Setters.Add(setter);
                        newStyle.Setters.Add(new Setter(VerticalAlignmentProperty, VerticalAlignment.Center));
                        dgtc.ElementStyle = newStyle;
                    }
                    // 
                    // initialize data triggers
                    var datatrigger = new DataTrigger()
                    {
                        Binding = new Binding("RuleMap[" + propertyName + "].HasError"),
                        Value = true
                    };
                    // adding the setters
                    datatrigger.Setters.Add(new Setter(ToolTipProperty, new Binding("RuleMap[" + propertyName + "].ErrorMessage")));
                    // Use bindings to the DataGrid properties so error colors update when theme changes
                    datatrigger.Setters.Add(new Setter(BorderBrushProperty, new Binding(nameof(ErrorCellBorderBrush))
                    {
                        RelativeSource = new RelativeSource(RelativeSourceMode.FindAncestor, typeof(ValidationDataGrid), 1)
                    }));
                    datatrigger.Setters.Add(new Setter(BackgroundProperty, new Binding(nameof(ErrorCellBackgroundBrush))
                    {
                        RelativeSource = new RelativeSource(RelativeSourceMode.FindAncestor, typeof(ValidationDataGrid), 1)
                    }));
                    datatrigger.Setters.Add(new Setter(BorderThicknessProperty, new Thickness(1d)));
                    // 
                    dgtc.CellStyle.Triggers.Add(datatrigger);

                }

                if (column.GetType() == typeof(DataGridCheckBoxColumn))
                {
                    // check box
                    DataGridCheckBoxColumn dgtcbx = column as DataGridCheckBoxColumn;

                    // grid cell check box style — use this.CellStyle (see text column comment above)
                    if (dgtcbx.CellStyle == null)
                    {
                        dgtcbx.CellStyle = new Style(typeof(DataGridCell), CellStyle);
                    }
                    else
                    {
                        var newStyle = new Style(typeof(DataGridCell), CellStyle);
                        foreach (var setter in dgtcbx.CellStyle.Setters)
                            newStyle.Setters.Add(setter);
                        dgtcbx.CellStyle = newStyle;
                    }
                    //
                    // grid element style
                    if (dgtcbx.ElementStyle == null)
                    {
                        dgtcbx.ElementStyle = new Style(typeof(CheckBox), FindImplicitStyle<CheckBox>());
                    }
                    else
                    {
                        var newStyle = new Style(typeof(CheckBox), FindImplicitStyle<CheckBox>());
                        foreach (var setter in dgtcbx.ElementStyle.Setters)

                            newStyle.Setters.Add(setter);
                        newStyle.Setters.Add(new Setter(VerticalAlignmentProperty, VerticalAlignment.Center));
                        newStyle.Setters.Add(new Setter(HorizontalAlignmentProperty, HorizontalAlignment.Center));
                        dgtcbx.ElementStyle = newStyle;
                    }
                }
            }

        }

        /// <summary>
        /// Handles preview text input for double-precision numeric cells, validating the input.
        /// </summary>
        /// <param name="sender">The TextBox receiving the input.</param>
        /// <param name="e">Event data containing the text being input.</param>
        private void Double_PreviewTextInput(object sender, TextCompositionEventArgs e)
        {
            TextBox tBox = (TextBox)sender;
            string cmb = tBox.Text + e.Text;

            // Check if this could be a partial infinity input
            bool isPartialInfinity = NumberFormatHelper.IsPartialInfinityText(cmb);

            // Use the centralized validation helper
            bool isValid = NumberFormatHelper.IsValidNumericInput(
                e.Text,
                tBox.Text,
                tBox.SelectionStart,
                tBox.SelectedText,
                allowNegative: true,
                allowDecimal: true,
                allowScientific: true);

            // Also allow 'e', 'E' for scientific notation and infinity patterns
            if (!isValid)
            {
                if (e.Text == "e" || e.Text == "E")
                    isValid = true;
                else if (isPartialInfinity)
                    isValid = true;
            }

            e.Handled = !isValid;
        }

        /// <summary>
        /// Handles preview text input for integer numeric cells, validating the input.
        /// </summary>
        /// <param name="sender">The TextBox receiving the input.</param>
        /// <param name="e">Event data containing the text being input.</param>
        private void Int_PreviewTextInput(object sender, TextCompositionEventArgs e)
        {
            TextBox tBox = (TextBox)sender;
            e.Handled = !NumberFormatHelper.IsValidNumericInput(
                e.Text,
                tBox.Text,
                tBox.SelectionStart,
                tBox.SelectedText,
                allowNegative: true,
                allowDecimal: false,
                allowScientific: false);
        }

        /// <summary>
        /// Handles text changes for integer cells, clearing invalid input.
        /// </summary>
        /// <param name="sender">The TextBox containing the changed text.</param>
        /// <param name="e">Event data for the text change.</param>
        private void Int_TextChanged(object sender, TextChangedEventArgs e)
        {
            TextBox box = (TextBox)sender;
            int IntValue;
            // Allow partial inputs like just a negative sign
            if (NumberFormatHelper.TryParseInt(box.Text, out IntValue) == false &&
                !NumberFormatHelper.IsNegativeSign(box.Text))
            {
                // handles the situation where text has changed but is invalid. This occurs on keypress of selected cell where text is changed yet the previewtextinput event does not fire.
                if (box.Text.Length == 1)
                    box.Text = "";
            }
        }

        /// <summary>
        /// Handles text changes for double-precision cells, clearing invalid input.
        /// </summary>
        /// <param name="sender">The TextBox containing the changed text.</param>
        /// <param name="e">Event data for the text change.</param>
        private void Double_TextChanged(object sender, TextChangedEventArgs e)
        {
            TextBox box = (TextBox)sender;
            double DblValue;
            if (NumberFormatHelper.TryParseDouble(box.Text, out DblValue) == false)
            {
                // Allow valid partial inputs during typing and infinity patterns
                if (NumberFormatHelper.IsValidPartialNumber(box.Text) ||
                    NumberFormatHelper.IsPartialInfinityText(box.Text))
                    return;
                // handles the situation where text has changed but is invalid. This occurs on keypress of selected cell where text is changed yet the previewtextinput event does not fire.
                if (box.Text.Length == 1)
                    box.Text = "";
            }
        }

        /// <summary>
        /// Handles the addition of grid rows and validates the new rows.
        /// </summary>
        /// <param name="startrow">The index where rows were added.</param>
        /// <param name="numrows">The number of rows that were added.</param>
        private void Grid_RowsAdded(int startrow, int numrows)
        {
            if (ItemsSource == null)
                return;
            IList<object> il = (IList<object>)ItemsSource;
            var newRowItems = new List<DataGridRowItem>();
            // Set the parent list for each new row item.
            for (int i = startrow, loopTo = startrow + (numrows - 1); i <= loopTo; i++)
            {
                if (!(il[i] is DataGridRowItem))
                    continue; // 'il(i).GetType.BaseType <> GetType(DataGridRowItem) Then Continue For
                newRowItems.Add((DataGridRowItem)il[i]);
                newRowItems.Last().ParentList = (System.Collections.ObjectModel.ObservableCollection<object>)ItemsSource;
            }
            // Force Validation on the New row items
            foreach (DataGridRowItem ri in newRowItems)
                ri.ForceValidation();
        }

        /// <summary>
        /// Validates all rows in the data grid table.
        /// </summary>
        public void ValidateTable()
        {
            if (SuppressValidation == true)
                return;
            if (ItemsSource == null)
                return;
            IList<object> itemsList = (IList<object>)ItemsSource;
            if (itemsList.Count == 0)
                return;
            // Do bulk validation
            PerformingBulkValidation = true;
            DataGridRowItem rowitem;
            for (int i = 0, loopTo = itemsList.Count - 1; i <= loopTo; i++)
            {
                if (!(itemsList[i] is DataGridRowItem))
                    continue;
                rowitem = (DataGridRowItem)itemsList[i];
                rowitem.ForceValidation();
            }
            PerformingBulkValidation = false;
            SuppressValidation = false;
            // Validate the first row.
            // This fires the unique rule if it is used.
            // Guard with the same is-check used in the loop: non-DataGridRowItem sources
            // (e.g., a DataView in a ValidationDataGrid not tied to DataGridRowItem rows)
            // would otherwise throw InvalidCastException here.
            if (itemsList[0] is DataGridRowItem firstRow)
            {
                firstRow.ForceValidation();
            }
        }

        /// <summary>
        /// Suppresses validation before pasting data.
        /// </summary>
        /// <param name="clipboardData">The clipboard data to be pasted.</param>
        /// <param name="cancelPaste">Reference to a flag that can cancel the paste operation.</param>
        private void Grid_PreviewPasteData(string[][] clipboardData, ref bool cancelPaste)
        {
            SuppressValidation = true;
        }

        /// <summary>
        /// Validates the table after pasting data.
        /// </summary>
        private void Grid_DataPasted()
        {
            SuppressValidation = false;
            ValidateTable();
        }

        /// <summary>
        /// Suppresses validation before deleting rows.
        /// </summary>
        /// <param name="rowindices">The indices of rows to be deleted.</param>
        /// <param name="cancel">Reference to a flag that can cancel the delete operation.</param>
        private void Grid_PreviewDeleteRows(List<int> rowindices, ref bool cancel)
        {
            SuppressValidation = true;
        }

        /// <summary>
        /// Validates the table after deleting rows.
        /// </summary>
        /// <param name="rowindices">The indices of the rows that were deleted.</param>
        private void Grid_RowsDeleted(List<int> rowindices)
        {
            SuppressValidation = false;
            ValidateTable();
        }

        #endregion

    }
}