/*
* NOTICE:
* The U.S. Army Corps of Engineers, Risk Management Center (USACE-RMC) makes no guarantees about
* the results, or appropriateness of outputs, obtained from this software.
*
* LIST OF CONDITIONS:
* Redistribution and use in source and binary forms, with or without modification, are permitted
* provided that the following conditions are met:
* ● Redistributions of source code must retain the above notice, this list of conditions, and the
* following disclaimer.
* ● Redistributions in binary form must reproduce the above notice, this list of conditions, and
* the following disclaimer in the documentation and/or other materials provided with the distribution.
* ● The names of the U.S. Government, the U.S. Army Corps of Engineers, the Institute for Water
* Resources, or the Risk Management Center may not be used to endorse or promote products derived
* from this software without specific prior written permission. Nor may the names of its contributors
* be used to endorse or promote products derived from this software without specific prior
* written permission.
*
* DISCLAIMER:
* THIS SOFTWARE IS PROVIDED BY THE U.S. ARMY CORPS OF ENGINEERS RISK MANAGEMENT CENTER
* (USACE-RMC) "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO,
* THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
* DISCLAIMED. IN NO EVENT SHALL USACE-RMC BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
* SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
* PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
* INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
* LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
* THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
*/
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Data;
using System.Windows.Input;
using System.Windows.Media;

namespace GenericControls
{
    /// <summary>
    /// A DataGrid with built-in validation support for cell values, including error highlighting and validation rules.
    /// </summary>
    /// <remarks>
    /// <para>
    /// <b> Authors: </b>
    /// <list type="bullet">
    ///     <item> Haden Smith, USACE Risk Management Center, cole.h.smith@usace.army.mil </item>
    /// </list>
    /// </para>
    /// </remarks>
    public sealed class ValidationDataGrid : CopyPasteDataGrid
    {

        #region Construction
        /// <summary>
        /// Initializes a new instance of the <see cref="ValidationDataGrid"/> class.
        /// Hooks into key DataGrid events and applies validation styling and behavior.
        /// </summary>
        public ValidationDataGrid()
        {
            // InitializeComponent();
            // AddHandler Loaded, AddressOf Grid_AutoGeneratedColumns
            // AddHandler AutoGeneratedColumns, AddressOf Grid_AutoGeneratedColumns
            AutoGeneratingColumn += Grid_AutoGeneratingColumn;
            Loaded += (sender, e) => ValidateTable();
            RowsAdded += Grid_RowsAdded;
            PreviewDeleteRows += Grid_PreviewDeleteRows;
            RowsDeleted += Grid_RowsDeleted;
            PreviewPasteData += Grid_PreviewPasteData;
            DataPasted += Grid_DataPasted;
            SelectedCellsChanged += (sender, e) =>
                {
                    if (((IEditableCollectionView)Items).IsEditingItem == false)
                        return;
                    if (e.AddedCells.Count > 0 && !IsReadOnly)
                    {
                        try
                        {
                            CommitEdit();
                        }
                        catch (Exception)
                        {
                            // Not sure why but for some reason this fails sometimes. The previous cell is being edited and the selected cell is changing.
                        }
                    }
                };
            Resources.Add(SystemColors.InactiveSelectionHighlightBrushKey, new SolidColorBrush(Colors.DarkGray));
            AutoGeneratedColumns += ValidationDataGrid_AutoGeneratedColumns;
        }

        #endregion

        #region Members

        private Dictionary<string, Type> _propertyTypes = new Dictionary<string, Type>();


        public static DependencyProperty ErrorCellBorderBrushProperty = DependencyProperty.Register(nameof(ErrorCellBorderBrush), typeof(Brush), typeof(ValidationDataGrid), new FrameworkPropertyMetadata(Brushes.Red));

        /// <summary>
        /// Brush used to highlight the border of cells with validation errors.
        /// </summary>
        public Brush ErrorCellBorderBrush
        {
            get
            {
                return (Brush)GetValue(ErrorCellBorderBrushProperty);
            }
            set
            {
                SetValue(ErrorCellBorderBrushProperty, value);
            }
        }

        public static DependencyProperty ErrorCellBackgroundBrushProperty = DependencyProperty.Register(nameof(ErrorCellBackgroundBrush), typeof(Brush), typeof(ValidationDataGrid), new FrameworkPropertyMetadata(new SolidColorBrush(Color.FromArgb(255, 247, 182, 175))));

        /// <summary>
        /// Brush used to highlight the background of cells with validation errors.
        /// </summary>
        public Brush ErrorCellBackgroundBrush
        {
            get
            {
                return (Brush)GetValue(ErrorCellBackgroundBrushProperty);
            }
            set
            {
                SetValue(ErrorCellBackgroundBrushProperty, value);
            }
        }


        /// <summary>
    /// Gets whether or not validation should be suppressed.
    /// </summary>
        public bool SuppressValidation { get; private set; } = false;


        public bool PerformingBulkValidation { get; private set; } = false;

        #endregion

        #region Methods

        protected override void OnCanExecuteBeginEdit(CanExecuteRoutedEventArgs e)
        {
            e.CanExecute = true;
            e.Handled = true;
        }

        /// <summary>
        /// Handles automatic column generation logic for display, style, and validation binding.
        /// </summary>
        /// <param name="sender">The DataGrid triggering the event.</param>
        /// <param name="e">Event data describing the generated column.</param>
        private void Grid_AutoGeneratingColumn(object sender, DataGridAutoGeneratingColumnEventArgs e)
        {
            if (e.PropertyName.Equals("RuleMap"))
            {
                e.Cancel = true;
                return;
            }
            if (ItemsSource == null)
                return;
            IList<object> il = (IList<object>)ItemsSource;
            DataGridRowItem d = (DataGridRowItem)il.FirstOrDefault();
            if (d == null)
                return;
            e.Cancel = !d.IsGridDisplayable(e.PropertyName);
            if (e.Cancel)
                return;
            string prettyheader = d.PropertyDisplayName(e.PropertyName);
            if (!(prettyheader == null) || !prettyheader.Equals(""))
                e.Column.Header = prettyheader;
            // 
            if (_propertyTypes.ContainsKey(e.PropertyName))
            {
                _propertyTypes[e.PropertyName] = e.PropertyType;
            }
            else
            {
                _propertyTypes.Add(e.PropertyName, e.PropertyType);
            }
        }

        /// <summary>
        /// Validates the autogenerated columns.
        /// </summary>
        /// <param name="sender">The DataGrid triggering the event.</param>
        /// <param name="e">Event data describing the generated column.</param>
        private void ValidationDataGrid_AutoGeneratedColumns(object sender, EventArgs e)
        {
            foreach (var column in Columns)
            {
                if (column.GetType() == typeof(DataGridTextColumn))
                {

                    // text column 
                    DataGridTextColumn dgtc = (DataGridTextColumn)column;
                    dgtc.Width = new DataGridLength(1d, DataGridLengthUnitType.Star);
                    string propertyName = ((Binding)dgtc.Binding).Path.Path.ToString();
                    // 
                    // First set the column editing style
                    // 
                    if (dgtc.EditingElementStyle == null)
                    {
                        dgtc.EditingElementStyle = new Style(typeof(TextBox));
                    }
                    else
                    {
                        var newStyle = new Style(typeof(TextBox));
                        foreach (var setter in dgtc.EditingElementStyle.Setters)
                            newStyle.Setters.Add(setter);
                        dgtc.EditingElementStyle = newStyle;
                    }
                    // 
                    // Dim textboxstyle As New Style(GetType(TextBox))
                    dgtc.EditingElementStyle.Setters.Add(new Setter(BorderThicknessProperty, new Thickness(0d)));
                    dgtc.EditingElementStyle.Setters.Add(new Setter(PaddingProperty, new Thickness(0d)));
                    dgtc.EditingElementStyle.Setters.Add(new Setter(HeightProperty, RowHeight));
                    dgtc.EditingElementStyle.Setters.Add(new Setter(VerticalContentAlignmentProperty, VerticalAlignment.Center));
                    switch (_propertyTypes[propertyName])
                    {
                        case var @case when @case == typeof(double):
                        case var case1 when case1 == typeof(float):
                        case var case2 when case2 == typeof(decimal):
                            {
                                var textBoxDoubleSetter = new EventSetter(PreviewTextInputEvent, new TextCompositionEventHandler(Double_PreviewTextInput));
                                var textBoxChangedDblSetter = new EventSetter(System.Windows.Controls.Primitives.TextBoxBase.TextChangedEvent, new TextChangedEventHandler(Double_TextChanged));
                                dgtc.EditingElementStyle.Setters.Add(textBoxDoubleSetter);
                                dgtc.EditingElementStyle.Setters.Add(textBoxChangedDblSetter);
                                break;
                            }
                        case var case3 when case3 == typeof(long):
                        case var case4 when case4 == typeof(ulong):
                        case var case5 when case5 == typeof(int):
                        case var case6 when case6 == typeof(uint):
                        case var case7 when case7 == typeof(short):
                        case var case8 when case8 == typeof(ushort):
                        case var case9 when case9 == typeof(byte):
                        case var case10 when case10 == typeof(sbyte):
                            {
                                var textBoxIntegerSetter = new EventSetter(PreviewTextInputEvent, new TextCompositionEventHandler(Int_PreviewTextInput));
                                var textBoxChangedIntSetter = new EventSetter(System.Windows.Controls.Primitives.TextBoxBase.TextChangedEvent, new TextChangedEventHandler(Int_TextChanged));
                                dgtc.EditingElementStyle.Setters.Add(textBoxIntegerSetter);
                                dgtc.EditingElementStyle.Setters.Add(textBoxChangedIntSetter);
                                break;
                            }
                    }

                    // Set the cell style for error collection
                    // 
                    // grid cell style
                    if (dgtc.CellStyle == null)
                    {
                        dgtc.CellStyle = new Style(typeof(DataGridCell));
                    }
                    else
                    {
                        var newStyle = new Style(typeof(DataGridCell));
                        foreach (var setter in dgtc.CellStyle.Setters)
                            newStyle.Setters.Add(setter);
                        dgtc.CellStyle = newStyle;
                    }
                    // 
                    // grid element style
                    if (dgtc.ElementStyle == null)
                    {
                        dgtc.ElementStyle = new Style(typeof(TextBlock));
                    }
                    else
                    {
                        var newStyle = new Style(typeof(TextBlock));
                        foreach (var setter in dgtc.ElementStyle.Setters)

                            newStyle.Setters.Add(setter);
                        newStyle.Setters.Add(new Setter(VerticalAlignmentProperty, VerticalAlignment.Center));
                        dgtc.ElementStyle = newStyle;
                    }
                    // 
                    // initialize data triggers
                    var datatrigger = new DataTrigger()
                    {
                        Binding = new Binding("RuleMap[" + propertyName + "].HasError"),
                        Value = true
                    };
                    // adding the setters
                    datatrigger.Setters.Add(new Setter(ToolTipProperty, new Binding("RuleMap[" + propertyName + "].ErrorMessage")));
                    datatrigger.Setters.Add(new Setter(BorderBrushProperty, ErrorCellBorderBrush));
                    datatrigger.Setters.Add(new Setter(BackgroundProperty, ErrorCellBackgroundBrush));
                    datatrigger.Setters.Add(new Setter(BorderThicknessProperty, new Thickness(1d)));
                    // 
                    dgtc.CellStyle.Triggers.Add(datatrigger);

                }

                if (column.GetType() == typeof(DataGridCheckBoxColumn))
                {
                    // check box
                    DataGridCheckBoxColumn dgtcbx = column as DataGridCheckBoxColumn;

                    // grid cell check box style
                    if (dgtcbx.CellStyle == null)
                    {
                        dgtcbx.CellStyle = new Style(typeof(DataGridCell));
                    }
                    else
                    {
                        var newStyle = new Style(typeof(DataGridCell));
                        foreach (var setter in dgtcbx.CellStyle.Setters)
                            newStyle.Setters.Add(setter);
                        dgtcbx.CellStyle = newStyle;
                    }
                    // 
                    // grid element style
                    if (dgtcbx.ElementStyle == null)
                    {
                        dgtcbx.ElementStyle = new Style(typeof(CheckBox));
                    }
                    else
                    {
                        var newStyle = new Style(typeof(CheckBox));
                        foreach (var setter in dgtcbx.ElementStyle.Setters)

                            newStyle.Setters.Add(setter);
                        newStyle.Setters.Add(new Setter(VerticalAlignmentProperty, VerticalAlignment.Center));
                        newStyle.Setters.Add(new Setter(HorizontalAlignmentProperty, HorizontalAlignment.Center));
                        dgtcbx.ElementStyle = newStyle;
                    }
                }
            }

        }

        /// <summary>
        /// Handles double text input and previews.
        /// </summary>
        /// <param name="sender">The DataGrid triggering the event.</param>
        /// <param name="e">Event data describing the generated column.</param>
        private void Double_PreviewTextInput(object sender, TextCompositionEventArgs e)
        {
            TextBox tBox = (TextBox)sender;
            string cmb = tBox.Text + e.Text;

            // Check if this could be a partial infinity input
            bool isPartialInfinity = NumberFormatHelper.IsPartialInfinityText(cmb);

            // Use the centralized validation helper
            bool isValid = NumberFormatHelper.IsValidNumericInput(
                e.Text,
                tBox.Text,
                tBox.SelectionStart,
                tBox.SelectedText,
                allowNegative: true,
                allowDecimal: true,
                allowScientific: true);

            // Also allow 'e', 'E' for scientific notation and infinity patterns
            if (!isValid)
            {
                if (e.Text == "e" || e.Text == "E")
                    isValid = true;
                else if (isPartialInfinity)
                    isValid = true;
            }

            e.Handled = !isValid;
        }

        /// <summary>
        /// Handles int text input and previews.
        /// </summary>
        /// <param name="sender">The DataGrid triggering the event.</param>
        /// <param name="e">Event data describing the generated column.</param>
        private void Int_PreviewTextInput(object sender, TextCompositionEventArgs e)
        {
            TextBox tBox = (TextBox)sender;
            e.Handled = !NumberFormatHelper.IsValidNumericInput(
                e.Text,
                tBox.Text,
                tBox.SelectionStart,
                tBox.SelectedText,
                allowNegative: true,
                allowDecimal: false,
                allowScientific: false);
        }

        /// <summary>
        /// Handles text changes in the cell.
        /// </summary>
        /// <param name="sender">The DataGrid triggering the event.</param>
        /// <param name="e">Event data describing the generated column.</param>
        private void Int_TextChanged(object sender, TextChangedEventArgs e)
        {
            TextBox box = (TextBox)sender;
            int IntValue;
            // Allow partial inputs like just a negative sign
            if (NumberFormatHelper.TryParseInt(box.Text, out IntValue) == false &&
                !NumberFormatHelper.IsNegativeSign(box.Text))
            {
                // handles the situation where text has changed but is invalid. This occurs on keypress of selected cell where text is changed yet the previewtextinput event does not fire.
                if (box.Text.Length == 1)
                    box.Text = "";
            }
        }

        /// <summary>
        /// Handles text changes in the cell.
        /// </summary>
        /// <param name="sender">The DataGrid triggering the event.</param>
        /// <param name="e">Event data describing the generated columns.</param>
        private void Double_TextChanged(object sender, TextChangedEventArgs e)
        {
            TextBox box = (TextBox)sender;
            double DblValue;
            if (NumberFormatHelper.TryParseDouble(box.Text, out DblValue) == false)
            {
                // Allow valid partial inputs during typing and infinity patterns
                if (NumberFormatHelper.IsValidPartialNumber(box.Text) ||
                    NumberFormatHelper.IsPartialInfinityText(box.Text))
                    return;
                // handles the situation where text has changed but is invalid. This occurs on keypress of selected cell where text is changed yet the previewtextinput event does not fire.
                if (box.Text.Length == 1)
                    box.Text = "";
            }
        }

        /// <summary>
        /// Handles adding grid rows and validates if possible with chosen parameters.
        /// </summary>
        /// <param name="startrow">Index for starting the row.</param>
        /// <param name="numrows">Number of total rows to be added.</param>
        private void Grid_RowsAdded(int startrow, int numrows)
        {
            if (ItemsSource == null)
                return;
            IList<object> il = (IList<object>)ItemsSource;
            var newRowItems = new List<DataGridRowItem>();
            // Set the parent list for each new row item.
            for (int i = startrow, loopTo = startrow + (numrows - 1); i <= loopTo; i++)
            {
                if (!(il[i] is DataGridRowItem))
                    continue; // 'il(i).GetType.BaseType <> GetType(DataGridRowItem) Then Continue For
                newRowItems.Add((DataGridRowItem)il[i]);
                newRowItems.Last().ParentList = (System.Collections.ObjectModel.ObservableCollection<object>)ItemsSource;
            }
            // Force Validation on the New row items
            foreach (DataGridRowItem ri in newRowItems)
                ri.ForceValidation();
        }

        /// <summary>
    /// Validate the table.
    /// </summary>
        public void ValidateTable()
        {
            if (SuppressValidation == true)
                return;
            if (ItemsSource == null)
                return;
            IList<object> itemsList = (IList<object>)ItemsSource;
            if (itemsList.Count == 0)
                return;
            // Do bulk validation
            PerformingBulkValidation = true;
            DataGridRowItem rowitem;
            for (int i = 0, loopTo = itemsList.Count - 1; i <= loopTo; i++)
            {
                if (!(itemsList[i] is DataGridRowItem))
                    continue;
                rowitem = (DataGridRowItem)itemsList[i];
                rowitem.ForceValidation();
            }
            PerformingBulkValidation = false;
            SuppressValidation = false;
            // Validate the first row.
            // This fires the unique rule if it is used
            rowitem = (DataGridRowItem)itemsList[0];
            rowitem.ForceValidation();
        }

        /// <summary>
    /// On preview paste data, suppress validation.
    /// </summary>
        private void Grid_PreviewPasteData(string[][] clipboardData, ref bool cancelPaste)
        {
            SuppressValidation = true;
        }

        /// <summary>
    /// Validate table after pasting data.
    /// </summary>
        private void Grid_DataPasted()
        {
            SuppressValidation = false;
            ValidateTable();
        }

        /// <summary>
    /// On preview delete rows, suppress validation.
    /// </summary>
        private void Grid_PreviewDeleteRows(List<int> rowindices, ref bool cancel)
        {
            SuppressValidation = true;
        }

        /// <summary>
    /// Validate table after deleting rows.
    /// </summary>
        private void Grid_RowsDeleted(List<int> rowindices)
        {
            SuppressValidation = false;
            ValidateTable();
        }

        #endregion

    }
}