<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">
  <PropertyGroup>
    <TargetFrameworks>net9.0-windows</TargetFrameworks>
    <UseWPF>true</UseWPF>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
    <RootNamespace>ExpressionParserControls</RootNamespace>
    <AssemblyName>ExpressionParserControls</AssemblyName>

    <GenerateDocumentationFile>True</GenerateDocumentationFile>
    <EmbedUntrackedSources>true</EmbedUntrackedSources>
    <DebugType>embedded</DebugType>

    <Description>WPF controls for the ExpressionParser library, providing expression editing components for Windows applications.</Description>
    <PackageProjectUrl>https://github.com/USACE-RMC/ExpressionParser</PackageProjectUrl>
    <RepositoryUrl>https://github.com/USACE-RMC/ExpressionParser</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <Title>ExpressionParserControls</Title>
    <GeneratePackageOnBuild>False</GeneratePackageOnBuild>
    <Company>USACE-RMC</Company>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <PackageTags>expression parser; WPF controls; formula editor; expression editor</PackageTags>
    <PackageLicenseExpression>BSD-3-Clause</PackageLicenseExpression>
    <PackageRequireLicenseAcceptance>True</PackageRequireLicenseAcceptance>
    <PackageId>RMC.ExpressionParserControls</PackageId>
    <Version>1.0.0</Version>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Debug|net9.0-windows|AnyCPU'">
    <NoWarn />
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Release|net9.0-windows|AnyCPU'">
    <NoWarn />
  </PropertyGroup>

  <ItemGroup>
    <!--https://github.com/dotnet/reproducible-builds-->
    <PackageReference Include="DotNet.ReproducibleBuilds" Version="1.2.25">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
    </PackageReference>
    <!--https://github.com/dotnet/sourcelink/tree/main-->
    <PackageReference Include="Microsoft.SourceLink.GitHub" Version="8.0.0">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="System.Drawing.Common" Version="9.0.0" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="ExpressionParser">
      <HintPath>..\..\..\expression-parser\ExpressionParser\bin\Debug\net9.0\ExpressionParser.dll</HintPath>
    </Reference>
  </ItemGroup>
  
</Project>
