<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <RootNamespace>DatabaseControls</RootNamespace>
    <AssemblyName>DatabaseControls</AssemblyName>
    <OutputType>Library</OutputType>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
  </PropertyGroup>

  <ItemGroup>
    <Page Update="Resources\TableViewerResources.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Resources\*.png" />
    <Resource Include="Resources\*.ico" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ExpressionParserControls\ExpressionParserControls.csproj" />
    <ProjectReference Include="..\GenericControls\GenericControls.csproj" />
    <ProjectReference Include="..\OxyPlotControls\OxyPlotControls.csproj" />
    <ProjectReference Include="..\Themes\Themes.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="DatabaseManager">
      <HintPath>..\..\..\database-management\DatabaseManager\bin\Debug\net9.0\DatabaseManager.dll</HintPath>
    </Reference>
    <Reference Include="ExpressionParser">
      <HintPath>..\..\..\expression-parser\ExpressionParser\bin\Debug\net9.0\ExpressionParser.dll</HintPath>
    </Reference>
    <Reference Include="Numerics">
      <HintPath>..\..\..\numerics\Numerics\bin\Debug\net9.0\Numerics.dll</HintPath>
    </Reference>
    <Reference Include="OxyPlot">
      <HintPath>..\..\..\oxyplot\Source\OxyPlot.Wpf\bin\Debug\net9.0-windows\OxyPlot.dll</HintPath>
    </Reference>
    <Reference Include="OxyPlot.Wpf">
      <HintPath>..\..\..\oxyplot\Source\OxyPlot.Wpf\bin\Debug\net9.0-windows\OxyPlot.Wpf.dll</HintPath>
    </Reference>
    <Reference Include="OxyPlot.Wpf.Shared">
      <HintPath>..\..\..\oxyplot\Source\OxyPlot.Wpf\bin\Debug\net9.0-windows\OxyPlot.Wpf.Shared.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
