<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <Description>OxyPlot WPF unit tests</Description>
    <TreatWarningsAsErrors>false</TreatWarningsAsErrors>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\OxyPlot.ExampleLibrary\OxyPlot.ExampleLibrary.csproj" />
    <ProjectReference Include="..\..\src\OxyPlot\OxyPlot\OxyPlot.csproj" />
    <ProjectReference Include="..\..\src\OxyPlot\OxyPlot.Wpf\OxyPlot.Wpf.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="NSubstitute" />
    <PackageReference Include="NUnit" />
    <PackageReference Include="NUnit3TestAdapter" />
  </ItemGroup>
</Project>
