Imports System.ComponentModel

Public NotInheritable Class ValidationDataGrid
    Inherits CopyPasteDataGrid

#Region "Construction"

    Public Sub New()
        'InitializeComponent();
        'AddHandler Loaded, AddressOf Grid_AutoGeneratedColumns
        'AddHandler AutoGeneratedColumns, AddressOf Grid_AutoGeneratedColumns
        AddHandler AutoGeneratingColumn, AddressOf Grid_AutoGeneratingColumn
        AddHandler Loaded, Sub(sender As Object, e As RoutedEventArgs) ValidateTable()
        AddHandler RowsAdded, AddressOf Grid_RowsAdded
        AddHandler PreviewDeleteRows, AddressOf Grid_PreviewDeleteRows
        AddHandler RowsDeleted, AddressOf Grid_RowsDeleted
        AddHandler Me.PreviewPasteData, AddressOf Grid_PreviewPasteData
        AddHandler DataPasted, AddressOf Grid_DataPasted
        AddHandler SelectedCellsChanged, Sub(sender As Object, e As SelectedCellsChangedEventArgs)
                                             If CType(Items, IEditableCollectionView).IsEditingItem = False Then Exit Sub
                                             If e.AddedCells.Count > 0 AndAlso Not IsReadOnly Then
                                                 Try
                                                     CommitEdit()
                                                 Catch ex As Exception
                                                     'Not sure why but for some reason this fails sometimes. The previous cell is being edited and the selected cell is changing.
                                                 End Try
                                             End If
                                         End Sub
        Resources.Add(SystemColors.InactiveSelectionHighlightBrushKey, New SolidColorBrush(Colors.DarkGray))
    End Sub

#End Region

#Region "Members"

    Private _propertyTypes As New Dictionary(Of String, Type)


    Public Shared ErrorCellBorderBrushProperty As DependencyProperty = DependencyProperty.Register(NameOf(ErrorCellBorderBrush), GetType(Brush), GetType(ValidationDataGrid), New FrameworkPropertyMetadata(Brushes.Red))

    Public Property ErrorCellBorderBrush As Brush
        Get
            Return CType(GetValue(ErrorCellBorderBrushProperty), Brush)
        End Get
        Set(value As Brush)
            SetValue(ErrorCellBorderBrushProperty, value)
        End Set
    End Property

    Public Shared ErrorCellBackgroundBrushProperty As DependencyProperty = DependencyProperty.Register(NameOf(ErrorCellBackgroundBrush), GetType(Brush), GetType(ValidationDataGrid), New FrameworkPropertyMetadata(New SolidColorBrush(Color.FromArgb(255, 247, 182, 175))))

    Public Property ErrorCellBackgroundBrush As Brush
        Get
            Return CType(GetValue(ErrorCellBackgroundBrushProperty), Brush)
        End Get
        Set(value As Brush)
            SetValue(ErrorCellBackgroundBrushProperty, value)
        End Set
    End Property


    ''' <summary>
    ''' Gets whether or not validation should be suppressed.
    ''' </summary>
    Public ReadOnly Property SuppressValidation As Boolean = False


    Public ReadOnly Property PerformingBulkValidation As Boolean = False

#End Region

#Region "Methods"

    Protected Overrides Sub OnCanExecuteBeginEdit(e As Input.CanExecuteRoutedEventArgs)
        e.CanExecute = True
        e.Handled = True
    End Sub

    Private Sub Grid_AutoGeneratingColumn(sender As Object, e As DataGridAutoGeneratingColumnEventArgs)
        If e.PropertyName.Equals("RuleMap") Then e.Cancel = True : Exit Sub
        If IsNothing(ItemsSource) Then Exit Sub
        Dim il As IList(Of Object) = CType(ItemsSource, IList(Of Object))
        Dim d As DataGridRowItem = CType(il.FirstOrDefault, DataGridRowItem)
        If IsNothing(d) Then Exit Sub
        e.Cancel = Not d.IsGridDisplayable(e.PropertyName)
        If e.Cancel Then Exit Sub
        Dim prettyheader As String = d.PropertyDisplayName(e.PropertyName)
        If Not IsNothing(prettyheader) OrElse Not prettyheader.Equals("") Then e.Column.Header = prettyheader
        '
        If _propertyTypes.ContainsKey(e.PropertyName) Then
            _propertyTypes(e.PropertyName) = e.PropertyType
        Else
            _propertyTypes.Add(e.PropertyName, e.PropertyType)
        End If
    End Sub
    Private Sub ValidationDataGrid_AutoGeneratedColumns(sender As Object, e As EventArgs) Handles Me.AutoGeneratedColumns
        For Each column In Columns
            If column.GetType() = GetType(DataGridTextColumn) Then

                'text column 
                Dim dgtc As DataGridTextColumn = DirectCast(column, DataGridTextColumn)
                dgtc.Width = New DataGridLength(1, DataGridLengthUnitType.Star)
                Dim propertyName As String = CType(dgtc.Binding, Binding).Path.Path.ToString
                '
                'First set the column editing style
                '
                If IsNothing(dgtc.EditingElementStyle) Then
                    dgtc.EditingElementStyle = New Style(GetType(TextBox))
                Else
                    Dim newStyle As New Style(GetType(TextBox))
                    For Each setter In dgtc.EditingElementStyle.Setters
                        newStyle.Setters.Add(setter)
                    Next
                    dgtc.EditingElementStyle = newStyle
                End If
                '
                'Dim textboxstyle As New Style(GetType(TextBox))
                dgtc.EditingElementStyle.Setters.Add(New Setter(TextBox.BorderThicknessProperty, New Thickness(0)))
                dgtc.EditingElementStyle.Setters.Add(New Setter(TextBox.PaddingProperty, New Thickness(0)))
                dgtc.EditingElementStyle.Setters.Add(New Setter(TextBox.HeightProperty, RowHeight))
                dgtc.EditingElementStyle.Setters.Add(New Setter(TextBox.VerticalContentAlignmentProperty, VerticalAlignment.Center))
                Select Case _propertyTypes(propertyName)
                    Case GetType(Double), GetType(Single), GetType(Decimal)
                        Dim textBoxDoubleSetter As New EventSetter(TextBox.PreviewTextInputEvent, New Input.TextCompositionEventHandler(AddressOf Double_PreviewTextInput))
                        Dim textBoxChangedDblSetter As New EventSetter(TextBox.TextChangedEvent, New TextChangedEventHandler(AddressOf Double_TextChanged))
                        dgtc.EditingElementStyle.Setters.Add(textBoxDoubleSetter)
                        dgtc.EditingElementStyle.Setters.Add(textBoxChangedDblSetter)
                    Case GetType(Long), GetType(ULong), GetType(Integer), GetType(UInteger), GetType(Short), GetType(UShort), GetType(Byte), GetType(SByte)
                        Dim textBoxIntegerSetter As New EventSetter(TextBox.PreviewTextInputEvent, New Input.TextCompositionEventHandler(AddressOf Int_PreviewTextInput))
                        Dim textBoxChangedIntSetter As New EventSetter(TextBox.TextChangedEvent, New TextChangedEventHandler(AddressOf Int_TextChanged))
                        dgtc.EditingElementStyle.Setters.Add(textBoxIntegerSetter)
                        dgtc.EditingElementStyle.Setters.Add(textBoxChangedIntSetter)
                End Select

                'Set the cell style for error collection
                '
                'grid cell style
                If IsNothing(dgtc.CellStyle) Then
                    dgtc.CellStyle = New Style(GetType(DataGridCell))
                Else
                    Dim newStyle = New Style(GetType(DataGridCell))
                    For Each setter In dgtc.CellStyle.Setters
                        newStyle.Setters.Add(setter)
                    Next
                    dgtc.CellStyle = newStyle
                End If
                '
                'grid element style
                If IsNothing(dgtc.ElementStyle) Then
                    dgtc.ElementStyle = New Style(GetType(TextBlock))
                Else
                    Dim newStyle = New Style(GetType(TextBlock))
                    For Each setter In dgtc.ElementStyle.Setters
                        newStyle.Setters.Add(setter)

                    Next
                    newStyle.Setters.Add(New Setter(VerticalAlignmentProperty, VerticalAlignment.Center))
                    dgtc.ElementStyle = newStyle
                End If
                '
                'initialize data triggers
                Dim datatrigger As New DataTrigger With {
                        .Binding = New Binding("RuleMap[" & propertyName & "].HasError"),
                        .Value = True
                    }
                'adding the setters
                datatrigger.Setters.Add(New Setter(DataGridCell.ToolTipProperty, New Binding("RuleMap[" & propertyName & "].ErrorMessage")))
                datatrigger.Setters.Add(New Setter(DataGridCell.BorderBrushProperty, ErrorCellBorderBrush))
                datatrigger.Setters.Add(New Setter(DataGridCell.BackgroundProperty, ErrorCellBackgroundBrush))
                datatrigger.Setters.Add(New Setter(DataGridCell.BorderThicknessProperty, New Thickness(1)))
                '
                dgtc.CellStyle.Triggers.Add(datatrigger)

            End If

            If column.GetType() = GetType(DataGridCheckBoxColumn) Then
                ' check box
                Dim dgtcbx As DataGridCheckBoxColumn = TryCast(column, DataGridCheckBoxColumn)

                'grid cell check box style
                If IsNothing(dgtcbx.CellStyle) Then
                    dgtcbx.CellStyle = New Style(GetType(DataGridCell))
                Else
                    Dim newStyle = New Style(GetType(DataGridCell))
                    For Each setter In dgtcbx.CellStyle.Setters
                        newStyle.Setters.Add(setter)
                    Next
                    dgtcbx.CellStyle = newStyle
                End If
                '
                'grid element style
                If IsNothing(dgtcbx.ElementStyle) Then
                    dgtcbx.ElementStyle = New Style(GetType(CheckBox))
                Else
                    Dim newStyle = New Style(GetType(CheckBox))
                    For Each setter In dgtcbx.ElementStyle.Setters
                        newStyle.Setters.Add(setter)

                    Next
                    newStyle.Setters.Add(New Setter(VerticalAlignmentProperty, VerticalAlignment.Center))
                    newStyle.Setters.Add(New Setter(HorizontalAlignmentProperty, HorizontalAlignment.Center))
                    dgtcbx.ElementStyle = newStyle
                End If
            End If
        Next

    End Sub

    Private Sub Double_PreviewTextInput(sender As Object, e As Input.TextCompositionEventArgs)
        Dim tBox As TextBox = DirectCast(sender, TextBox)
        Dim inf As String() = {"-inf", "-Inf", "-infinity", "-Infinity", "+inf", "+Inf", "+infinity", "+Infinity"}
        Dim validString As Boolean = False
        Dim cmb = tBox.Text + e.Text
        Dim DblValue As Double
        If Double.TryParse(cmb, DblValue) = False Then
            For Each strg In inf
                If cmb.Length > strg.Length Then Continue For
                If strg.Substring(0, cmb.Length) = cmb Then
                    validString = True
                    Exit For
                End If
            Next
        End If


        If Not Char.IsDigit(CChar(e.Text)) AndAlso (e.Text <> "e" AndAlso e.Text <> "E" AndAlso validString = False) Then e.Handled = True 'numeric only but allow 'e' and 'E' for scientific notation (1E-20)
        If e.Text = Chr(8) Then e.Handled = False 'allow Backspace
        If e.Text = " " Then e.Handled = True 'don't allow spaces
        If e.Text = "-" Then e.Handled = False 'AndAlso tBox.SelectionStart = 0 AndAlso tBox.Text.IndexOf("-") = -1 Then e.Handled = False 'allow negative which can occur after the e in scientific notation.
        If e.Text = "+" AndAlso tBox.SelectionStart = 0 AndAlso tBox.Text.IndexOf("+") = -1 Then e.Handled = False 'allow positive values
        If e.Text = "." Then 'allow one decimal
            If tBox.Text.IndexOf(".") = -1 Then e.Handled = False
            If tBox.SelectedText.IndexOf(".") > -1 Then e.Handled = False
        End If
        e.Handled = False
    End Sub

    Private Sub Int_PreviewTextInput(sender As Object, e As Input.TextCompositionEventArgs)
        Dim tBox As TextBox = DirectCast(sender, TextBox)
        If Not Char.IsDigit(CChar(e.Text)) Then e.Handled = True 'numeric only
        If e.Text = Chr(8) Then e.Handled = False 'allow Backspace
        If e.Text = " " Then e.Handled = True 'don't allow spaces
        If e.Text = "-" And tBox.SelectionStart = 0 And tBox.Text.IndexOf("-") = -1 Then e.Handled = False 'allow negative
    End Sub

    Private Sub Int_TextChanged(sender As Object, e As TextChangedEventArgs)
        Dim box As TextBox = CType(sender, TextBox)
        Dim IntValue As Integer
        If Integer.TryParse(box.Text, IntValue) = False And box.Text <> "-" Then
            'handles the situation where text has changed but is invalid. This occurs on keypress of selected cell where text is changed yet the previewtextinput event does not fire.
            If box.Text.Length = 1 Then box.Text = ""
        End If
    End Sub

    Private Sub Double_TextChanged(sender As Object, e As TextChangedEventArgs)
        Dim box As TextBox = CType(sender, TextBox)
        Dim DblValue As Double
        If Double.TryParse(box.Text, DblValue) = False Then
            'handles the situation where text has changed but is invalid. This occurs on keypress of selected cell where text is changed yet the previewtextinput event does not fire.
            If box.Text = "+" Or box.Text = "-" Or box.Text = "-." Or box.Text = "." Then Exit Sub
            If box.Text.Length = 1 Then box.Text = ""
        End If
    End Sub

    Private Sub Grid_RowsAdded(startrow As Integer, numrows As Integer)
        If IsNothing(ItemsSource) Then Exit Sub
        Dim il As IList(Of Object) = CType(ItemsSource, IList(Of Object))
        Dim newRowItems As New List(Of DataGridRowItem)
        'Set the parent list for each new row item.
        For i As Integer = startrow To startrow + (numrows - 1)
            If Not TypeOf il(i) Is DataGridRowItem Then Continue For ''il(i).GetType.BaseType <> GetType(DataGridRowItem) Then Continue For
            newRowItems.Add(DirectCast(il(i), DataGridRowItem))
            newRowItems.Last.ParentList = DirectCast(ItemsSource, ObjectModel.ObservableCollection(Of Object))
        Next
        ' Force Validation on the New row items
        For Each ri As DataGridRowItem In newRowItems
            ri.ForceValidation()
        Next
    End Sub

    ''' <summary>
    ''' Validate the table.
    ''' </summary>
    Public Sub ValidateTable()
        If SuppressValidation = True Then Exit Sub
        If IsNothing(ItemsSource) Then Exit Sub
        Dim itemsList As IList(Of Object) = CType(ItemsSource, IList(Of Object))
        If itemsList.Count = 0 Then Exit Sub
        'Do bulk validation
        _PerformingBulkValidation = True
        Dim rowitem As DataGridRowItem
        For i As Integer = 0 To itemsList.Count - 1
            If Not TypeOf itemsList(i) Is DataGridRowItem Then Continue For
            rowitem = DirectCast(itemsList(i), DataGridRowItem)
            rowitem.ForceValidation()
        Next
        _PerformingBulkValidation = False
        _SuppressValidation = False
        ' Validate the first row.
        ' This fires the unique rule if it is used
        rowitem = DirectCast(itemsList(0), DataGridRowItem)
        rowitem.ForceValidation()
    End Sub

    ''' <summary>
    ''' On preview paste data, suppress validation.
    ''' </summary>
    Private Sub Grid_PreviewPasteData(clipboardData As String()(), ByRef cancelPaste As Boolean)
        _SuppressValidation = True
    End Sub

    ''' <summary>
    ''' Validate table after pasting data.
    ''' </summary>
    Private Sub Grid_DataPasted()
        _SuppressValidation = False
        ValidateTable()
    End Sub

    ''' <summary>
    ''' On preview delete rows, suppress validation.
    ''' </summary>
    Private Sub Grid_PreviewDeleteRows(rowindices As List(Of Integer), ByRef cancel As Boolean)
        _SuppressValidation = True
    End Sub

    ''' <summary>
    ''' Validate table after deleting rows.
    ''' </summary>
    Private Sub Grid_RowsDeleted(rowindices As List(Of Integer))
        _SuppressValidation = False
        ValidateTable()
    End Sub

#End Region

End Class
