<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <IsPackable>true</IsPackable>
    <IncludeBuildOutput>false</IncludeBuildOutput>
    <Version>1.0.1</Version>
    <NuspecFile>RMC.Wpf.Framework.Core.nuspec</NuspecFile>
    <NuspecBasePath>$(MSBuildProjectDirectory)</NuspecBasePath>
    <NuspecProperties>configuration=$(Configuration);version=$(Version)</NuspecProperties>
  </PropertyGroup>
</Project>
