<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <AssemblyOriginatorKeyFile>OxyPlot.Wpf.snk</AssemblyOriginatorKeyFile>
    <GeneratePackageOnBuild>false</GeneratePackageOnBuild>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <TreatWarningsAsErrors>false</TreatWarningsAsErrors>
    <LangVersion>8</LangVersion>
    <SignAssembly>true</SignAssembly>
    <Description>OxyPlot is a plotting library for .NET. This package targets WPF applications.</Description>
  </PropertyGroup>
  <ItemGroup>
    <None Include="OxyPlot.Wpf.snk" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\OxyPlot.Wpf.Shared\OxyPlot.Wpf.Shared.csproj" />
    <ProjectReference Include="..\OxyPlot\OxyPlot.csproj" />
  </ItemGroup>
</Project>
