
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows</TargetFramework>
    <RootNamespace>DatabaseControls.Demo</RootNamespace>
    <AssemblyName>DatabaseControls.Demo</AssemblyName>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="System.Data.SQLite" Version="2.0.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\DatabaseControls\DatabaseControls.csproj" />
    <ProjectReference Include="..\..\DatabaseManager\DatabaseManager.csproj" />
    <ProjectReference Include="..\..\Themes\Themes.csproj" />
  </ItemGroup>
  
  	<!-- Shared packages -->
	<ItemGroup>
		<PackageReference Include="System.Data.SQLite" Version="2.0.2" />
		<PackageReference Include="SourceGear.sqlite3" Version="3.50.4.5" />
	</ItemGroup>

</Project>
