<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows</TargetFramework>
    <RootNamespace>DatabaseControls.Demo</RootNamespace>
    <AssemblyName>DatabaseControls.Demo</AssemblyName>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\DatabaseControls\DatabaseControls.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="DatabaseManager">
      <HintPath>..\..\..\..\database-management\DatabaseManager\bin\Debug\net9.0\DatabaseManager.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
