<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net9.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <LangVersion>8</LangVersion>
    <Description>OxyPlot is a plotting library for .NET. This package is the base for WPF PlotView implementations.</Description>
    <GeneratePackageOnBuild>false</GeneratePackageOnBuild>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <SignAssembly>true</SignAssembly>
    <AssemblyOriginatorKeyFile>OxyPlot.Wpf.Shared.snk</AssemblyOriginatorKeyFile>
  </PropertyGroup>
  <ItemGroup>
    <None Include="OxyPlot.Wpf.Shared.snk" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\OxyPlot\OxyPlot.csproj" />
  </ItemGroup>
</Project>
