name: Integration

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  CI:
    uses: HydrologicEngineeringCenter/dotnet-workflows/.github/workflows/integration.yml@main
    with:
      dotnet-version: '10.0.x'
      run-tests: true
